# Generated by Django 5.2.4 on 2025-08-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Заголовок")),
                ("description", models.TextField(max_length=500, verbose_name="Содержимое")),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photo/blogs/", verbose_name="Изображение"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("publication_at", models.BooleanField(verbose_name="Признак публикации")),
                ("quantity_count", models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
